apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
spec:
  containers:
  - name: es
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    lifecycle:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              yes | /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
